$dbd_oracle_mm_opts = {
                        'META_MERGE' => {
                                          'build_requires' => {
                                                                'ExtUtils::MakeMaker' => 0,
                                                                'Test::Simple' => '0.90',
                                                                'DBI' => '1.51'
                                                              },
                                          'resources' => {
                                                           'repository' => {
                                                                             'web' => 'http://github.com/yanick/DBD-Oracle/tree',
                                                                             'type' => 'git',
                                                                             'url' => 'git://github.com/yanick/DBD-Oracle.git'
                                                                           },
                                                           'bugtracker' => {
                                                                             'web' => 'http://rt.cpan.org/Public/Dist/Display.html?Name=DBD-Oracle',
                                                                             'mailto' => 'bug-dbd-oracle at rt.cpan.org'
                                                                           },
                                                           'homepage' => 'http://search.cpan.org/dist/DBD-Oracle'
                                                         },
                                          'configure_requires' => {
                                                                    'DBI' => '1.51'
                                                                  }
                                        },
                        'PREREQ_PM' => {
                                         'DBI' => '1.51'
                                       },
                        'dist' => {
                                    'SUFFIX' => 'gz',
                                    'DIST_DEFAULT' => 'clean distcheck disttest tardist',
                                    'COMPRESS' => 'gzip -v9',
                                    'PREOP' => '$(MAKE) -f Makefile.old distdir'
                                  },
                        'clean' => {
                                     'FILES' => 'xstmp.c Oracle.xsi dll.base dll.exp sqlnet.log libOracle.def mk.pm DBD_ORA_OBJ.*'
                                   },
                        'INC' => '-IC:/cygwin/home/gecko/AP-5.24.3.2404-MSWin32-x64-404865/oracle-instantclient-win64/sdk/include -IC:/cygwin/home/gecko/AP-5.24.3.2404-MSWin32-x64-404865/oracle-instantclient-win64/rdbms/demo -IC:\Users\magja\graphviz-build-utilities\\lib\\auto\\DBI',
                        'LIBS' => [
                                    '-LC:/cygwin/home/gecko/AP-5.24.3.2404-MSWin32-x64-404865/DBD-Oracle -loci'
                                  ],
                        'ABSTRACT_FROM' => 'lib/DBD/Oracle.pm',
                        'DEFINE' => ' -Wall -Wno-comment -DUTF8_SUPPORT -DORA_OCI_VERSION=\\"12.2.0.1\\" -DORA_OCI_102 -DORA_OCI_112',
                        'OBJECT' => '$(O_FILES)',
                        'VERSION_FROM' => 'lib/DBD/Oracle.pm',
                        'AUTHOR' => 'Tim Bunce (dbi-users@perl.org)',
                        'NAME' => 'DBD::Oracle',
                        'LICENSE' => 'perl',
                        'DIR' => []
                      };
$dbd_oracle_mm_self = bless( {
                               'MKPATH' => '$(ABSPERLRUN) -MExtUtils::Command -e mkpath --',
                               'MAN1EXT' => '1',
                               'PERL_INCDEP' => 'C:\Users\magja\graphviz-build-utilities\\lib\\CORE',
                               'DEV_NULL' => '> NUL',
                               'FULLPERLRUNINST' => '$(FULLPERLRUN) "-I$(INST_ARCHLIB)" "-I$(INST_LIB)"',
                               'CHMOD' => '$(ABSPERLRUN) -MExtUtils::Command -e chmod --',
                               'LDFROM' => '$(OBJECT)',
                               'INSTALLVENDORLIB' => '',
                               'CI' => 'ci -u',
                               'PM' => {
                                         'lib/DBD/Oracle/Troubleshooting/Hpux.pod' => 'blib\\lib\\DBD\\Oracle\\Troubleshooting\\Hpux.pod',
                                         'lib/DBD/Oracle/GetInfo.pm' => 'blib\\lib\\DBD\\Oracle\\GetInfo.pm',
                                         'lib/DBD/Oracle/Troubleshooting/Vms.pod' => 'blib\\lib\\DBD\\Oracle\\Troubleshooting\\Vms.pod',
                                         'lib/DBD/Oracle/Troubleshooting/Aix.pod' => 'blib\\lib\\DBD\\Oracle\\Troubleshooting\\Aix.pod',
                                         'lib/DBD/Oracle/Troubleshooting/Linux.pod' => 'blib\\lib\\DBD\\Oracle\\Troubleshooting\\Linux.pod',
                                         'mk.pm' => '$(INST_LIB)\\DBD\\mk.pm',
                                         'lib/DBD/Oracle/Troubleshooting.pod' => 'blib\\lib\\DBD\\Oracle\\Troubleshooting.pod',
                                         'lib/DBD/Oracle/Troubleshooting/Win32.pod' => 'blib\\lib\\DBD\\Oracle\\Troubleshooting\\Win32.pod',
                                         'lib/DBD/Oracle.pm' => 'blib\\lib\\DBD\\Oracle.pm',
                                         'lib/DBD/Oracle/Troubleshooting/Win64.pod' => 'blib\\lib\\DBD\\Oracle\\Troubleshooting\\Win64.pod',
                                         'lib/DBD/Oracle/Object.pm' => 'blib\\lib\\DBD\\Oracle\\Object.pm',
                                         'lib/DBD/Oracle/Troubleshooting/Sun.pod' => 'blib\\lib\\DBD\\Oracle\\Troubleshooting\\Sun.pod',
                                         'lib/DBD/Oracle/Troubleshooting/Macos.pod' => 'blib\\lib\\DBD\\Oracle\\Troubleshooting\\Macos.pod',
                                         'lib/DBD/Oracle/Troubleshooting/Cygwin.pod' => 'blib\\lib\\DBD\\Oracle\\Troubleshooting\\Cygwin.pod'
                                       },
                               'ABSPERLRUNINST' => '$(ABSPERLRUN) "-I$(INST_ARCHLIB)" "-I$(INST_LIB)"',
                               'MV' => '$(ABSPERLRUN) -MExtUtils::Command -e mv --',
                               'XS_DEFINE_VERSION' => '-D$(XS_VERSION_MACRO)=\\"$(XS_VERSION)\\"',
                               'INSTALLSITEARCH' => 'C:\Users\magja\graphviz-build-utilities\\site\\lib',
                               'NOOP' => 'rem',
                               'LDDLFLAGS' => '-mdll -s -static-libgcc -static-libstdc++ -L"C:\Users\magja\graphviz-build-utilities\\lib\\CORE" -L"C:\\MinGW\\x86_64-w64-mingw32\\lib"',
                               'MAKEMAKER' => 'C:/cygwin/home/gecko/tmp/perl-oexhrvnteqvgqcduqvgctefvvbignxweep/lib/ExtUtils/MakeMaker.pm',
                               'DESTINSTALLMAN3DIR' => '$(DESTDIR)$(INSTALLMAN3DIR)',
                               'PERLRUN' => '$(PERL)',
                               'PERL_ARCHLIB' => 'C:\Users\magja\graphviz-build-utilities\\lib',
                               'TO_UNIX' => '$(NOECHO) $(NOOP)',
                               'BUILD_REQUIRES' => {},
                               'DLBASE' => '$(BASEEXT)',
                               'INSTALLSITELIB' => 'C:\Users\magja\graphviz-build-utilities\\site\\lib',
                               'CP' => '$(ABSPERLRUN) -MExtUtils::Command -e cp --',
                               'VENDORPREFIX' => '',
                               'VERSION_FROM' => 'lib/DBD/Oracle.pm',
                               'PL_FILES' => {},
                               'DIR' => $dbd_oracle_mm_opts->{'DIR'},
                               'clean' => $dbd_oracle_mm_opts->{'clean'},
                               'VERSION_MACRO' => 'VERSION',
                               'PERM_RWX' => 755,
                               'MACROEND' => '',
                               'VERBINST' => 0,
                               'PERL_ARCHLIBDEP' => 'C:\Users\magja\graphviz-build-utilities\\lib',
                               'NAME' => 'DBD::Oracle',
                               'INSTALLVENDORMAN1DIR' => '',
                               'MAKE_APERL_FILE' => 'Makefile.aperl',
                               'O_FILES' => [
                                              'Oracle.o',
                                              'dbdimp.o',
                                              'oci8.o'
                                            ],
                               'DLEXT' => 'dll',
                               'TRUE' => '$(ABSPERLRUN)  -e "exit 0" --',
                               'ZIPFLAGS' => '-r',
                               'INSTALLDIRS' => 'perl',
                               'XS_VERSION_MACRO' => 'XS_VERSION',
                               'INSTALLSITEBIN' => 'C:\Users\magja\graphviz-build-utilities\\site\\bin',
                               'INST_SCRIPT' => 'blib\\script',
                               'FIXIN' => 'pl2bat.bat',
                               'DISTNAME' => 'DBD-Oracle',
                               'INST_MAN3DIR' => 'blib\\man3',
                               'SUFFIX' => '.gz',
                               'EXPORT_LIST' => '$(BASEEXT).def',
                               'ZIP' => 'zip',
                               'INSTALLVENDORSCRIPT' => '',
                               'INST_LIBDIR' => '$(INST_LIB)\\DBD',
                               'MM_Win32_VERSION' => '7.3',
                               'PERL_ARCHIVE' => '$(PERL_INC)\\libperl524.a',
                               'VERSION_SYM' => '1_74',
                               'ECHO' => '$(ABSPERLRUN) -l -e "binmode STDOUT, qq{{:raw}}; print qq{{@ARGV}}" --',
                               'USEMAKEFILE' => '-f',
                               'WARN_IF_OLD_PACKLIST' => '$(ABSPERLRUN) -MExtUtils::Command::MM -e warn_if_old_packlist --',
                               'INST_LIB' => 'blib\\lib',
                               'DESTINSTALLVENDORMAN1DIR' => '$(DESTDIR)$(INSTALLVENDORMAN1DIR)',
                               'DESTINSTALLVENDORBIN' => '$(DESTDIR)$(INSTALLVENDORBIN)',
                               'DIRFILESEP' => '\\\\',
                               'SITEARCHEXP' => 'C:\Users\magja\graphviz-build-utilities\\site\\lib',
                               'DESTINSTALLSITEMAN3DIR' => '$(DESTDIR)$(INSTALLSITEMAN3DIR)',
                               'SITELIBEXP' => 'C:\Users\magja\graphviz-build-utilities\\site\\lib',
                               'MOD_INSTALL' => '$(ABSPERLRUN) -MExtUtils::Install -e "install([ from_to => {{@ARGV}}, verbose => \'$(VERBINST)\', uninstall_shadows => \'$(UNINST)\', dir_mode => \'$(PERM_DIR)\' ]);" --',
                               'PERL' => '"C:\Users\magja\graphviz-build-utilities\\bin\\perl.exe"',
                               'DEFINE_VERSION' => '-D$(VERSION_MACRO)=\\"$(VERSION)\\"',
                               'AUTHOR' => [
                                             'Tim Bunce (dbi-users@perl.org)'
                                           ],
                               'INSTALLBIN' => 'C:\Users\magja\graphviz-build-utilities\\bin',
                               'TEST_REQUIRES' => {},
                               'INSTALLVENDORMAN3DIR' => '',
                               'EXE_EXT' => '.exe',
                               'ABSPERLRUN' => '$(ABSPERL)',
                               'MAKE' => 'dmake',
                               'DESTINSTALLSITEHTMLDIR' => '$(DESTDIR)$(INSTALLSITEHTMLDIR)',
                               'META_MERGE' => $dbd_oracle_mm_opts->{'META_MERGE'},
                               'MM_REVISION' => 73000,
                               'INSTALLSITEHTMLDIR' => 'C:\Users\magja\graphviz-build-utilities\\html',
                               'OSNAME' => 'MSWin32',
                               'FULLPERLRUN' => '$(FULLPERL)',
                               'ECHO_N' => '$(ABSPERLRUN)  -e "print qq{{@ARGV}}" --',
                               'FIRST_MAKEFILE' => 'Makefile',
                               'TEST_F' => '$(ABSPERLRUN) -MExtUtils::Command -e test_f --',
                               'PERL_SRC' => undef,
                               'INST_ARCHLIB' => 'blib\\arch',
                               'INSTALLHTMLDIR' => 'C:\Users\magja\graphviz-build-utilities\\html',
                               'DESTINSTALLSITEARCH' => '$(DESTDIR)$(INSTALLSITEARCH)',
                               'TOUCH' => '$(ABSPERLRUN) -MExtUtils::Command -e touch --',
                               'BOOTDEP' => '',
                               'FULLPERL' => '"C:\Users\magja\graphviz-build-utilities\\bin\\perl.exe"',
                               'PARENT_NAME' => 'DBD',
                               'DESTDIR' => '',
                               'POSTOP' => '$(NOECHO) $(NOOP)',
                               'RM_F' => '$(ABSPERLRUN) -MExtUtils::Command -e rm_f --',
                               'DOC_INSTALL' => '$(ABSPERLRUN) -MExtUtils::Command::MM -e perllocal_install --',
                               'PERL_LIB' => 'C:\Users\magja\graphviz-build-utilities\\lib',
                               'INC' => '-IC:/cygwin/home/gecko/AP-5.24.3.2404-MSWin32-x64-404865/oracle-instantclient-win64/sdk/include -IC:/cygwin/home/gecko/AP-5.24.3.2404-MSWin32-x64-404865/oracle-instantclient-win64/rdbms/demo -IC:\Users\magja\graphviz-build-utilities\\lib\\auto\\DBI',
                               'MAKEFILE' => 'Makefile',
                               'SITEPREFIX' => 'C:\Users\magja\graphviz-build-utilities\\site',
                               'DESTINSTALLVENDORARCH' => '$(DESTDIR)$(INSTALLVENDORARCH)',
                               'PERLMAINCC' => '$(CC)',
                               'INST_ARCHLIBDIR' => '$(INST_ARCHLIB)\\DBD',
                               'COMPRESS' => 'gzip --best',
                               'PREFIX' => '$(PERLPREFIX)',
                               'SKIPHASH' => {},
                               'DESTINSTALLHTMLDIR' => '$(DESTDIR)$(INSTALLHTMLDIR)',
                               'DESTINSTALLVENDORSCRIPT' => '$(DESTDIR)$(INSTALLVENDORSCRIPT)',
                               'LDFLAGS' => '-s -static-libgcc -static-libstdc++ -L"C:\Users\magja\graphviz-build-utilities\\lib\\CORE" -L"C:\\MinGW\\x86_64-w64-mingw32\\lib"',
                               'UNINST' => 0,
                               'DESTINSTALLARCHLIB' => '$(DESTDIR)$(INSTALLARCHLIB)',
                               'VENDORARCHEXP' => '',
                               'INST_DYNAMIC' => '$(INST_ARCHAUTODIR)\\$(DLBASE).$(DLEXT)',
                               'INST_BOOT' => '$(INST_ARCHAUTODIR)\\$(BASEEXT).bs',
                               'TAR' => 'tar',
                               'DLSRC' => 'dl_win32.xs',
                               'DISTVNAME' => 'DBD-Oracle-1.74',
                               'INSTALLVENDORARCH' => '',
                               'NAME_SYM' => 'DBD_Oracle',
                               'VENDORLIBEXP' => '',
                               'LDLOADLIBS' => '"liboci.a" "C:\\MinGW\\x86_64-w64-mingw32\\lib\\libmoldname.a" "C:\\MinGW\\x86_64-w64-mingw32\\lib\\libkernel32.a" "C:\\MinGW\\x86_64-w64-mingw32\\lib\\libuser32.a" "C:\\MinGW\\x86_64-w64-mingw32\\lib\\libgdi32.a" "C:\\MinGW\\x86_64-w64-mingw32\\lib\\libwinspool.a" "C:\\MinGW\\x86_64-w64-mingw32\\lib\\libcomdlg32.a" "C:\\MinGW\\x86_64-w64-mingw32\\lib\\libadvapi32.a" "C:\\MinGW\\x86_64-w64-mingw32\\lib\\libshell32.a" "C:\\MinGW\\x86_64-w64-mingw32\\lib\\libole32.a" "C:\\MinGW\\x86_64-w64-mingw32\\lib\\liboleaut32.a" "C:\\MinGW\\x86_64-w64-mingw32\\lib\\libnetapi32.a" "C:\\MinGW\\x86_64-w64-mingw32\\lib\\libuuid.a" "C:\\MinGW\\x86_64-w64-mingw32\\lib\\libws2_32.a" "C:\\MinGW\\x86_64-w64-mingw32\\lib\\libmpr.a" "C:\\MinGW\\x86_64-w64-mingw32\\lib\\libwinmm.a" "C:\\MinGW\\x86_64-w64-mingw32\\lib\\libversion.a" "C:\\MinGW\\x86_64-w64-mingw32\\lib\\libodbc32.a" "C:\\MinGW\\x86_64-w64-mingw32\\lib\\libodbccp32.a" "C:\\MinGW\\x86_64-w64-mingw32\\lib\\libcomctl32.a"',
                               'PERM_RW' => 644,
                               'DESTINSTALLSITEMAN1DIR' => '$(DESTDIR)$(INSTALLSITEMAN1DIR)',
                               'DESTINSTALLVENDORHTMLDIR' => '$(DESTDIR)$(INSTALLVENDORHTMLDIR)',
                               'FULL_AR' => '',
                               'PERLRUNINST' => '$(PERLRUN) "-I$(INST_ARCHLIB)" "-I$(INST_LIB)"',
                               'UMASK_NULL' => 'umask 0',
                               'CC' => 'gcc',
                               'MAN3PODS' => {
                                               'lib/DBD/Oracle/Troubleshooting/Hpux.pod' => '$(INST_MAN3DIR)\\DBD.Oracle.Troubleshooting.Hpux.$(MAN3EXT)',
                                               'lib/DBD/Oracle/GetInfo.pm' => '$(INST_MAN3DIR)\\DBD.Oracle.GetInfo.$(MAN3EXT)',
                                               'lib/DBD/Oracle/Troubleshooting/Aix.pod' => '$(INST_MAN3DIR)\\DBD.Oracle.Troubleshooting.Aix.$(MAN3EXT)',
                                               'lib/DBD/Oracle/Troubleshooting/Vms.pod' => '$(INST_MAN3DIR)\\DBD.Oracle.Troubleshooting.Vms.$(MAN3EXT)',
                                               'lib/DBD/Oracle/Object.pm' => '$(INST_MAN3DIR)\\DBD.Oracle.Object.$(MAN3EXT)',
                                               'lib/DBD/Oracle/Troubleshooting/Win64.pod' => '$(INST_MAN3DIR)\\DBD.Oracle.Troubleshooting.Win64.$(MAN3EXT)',
                                               'lib/DBD/Oracle/Troubleshooting/Sun.pod' => '$(INST_MAN3DIR)\\DBD.Oracle.Troubleshooting.Sun.$(MAN3EXT)',
                                               'lib/DBD/Oracle/Troubleshooting/Macos.pod' => '$(INST_MAN3DIR)\\DBD.Oracle.Troubleshooting.Macos.$(MAN3EXT)',
                                               'lib/DBD/Oracle/Troubleshooting/Cygwin.pod' => '$(INST_MAN3DIR)\\DBD.Oracle.Troubleshooting.Cygwin.$(MAN3EXT)',
                                               'lib/DBD/Oracle/Troubleshooting/Linux.pod' => '$(INST_MAN3DIR)\\DBD.Oracle.Troubleshooting.Linux.$(MAN3EXT)',
                                               'lib/DBD/Oracle/Troubleshooting.pod' => '$(INST_MAN3DIR)\\DBD.Oracle.Troubleshooting.$(MAN3EXT)',
                                               'lib/DBD/Oracle.pm' => '$(INST_MAN3DIR)\\DBD.Oracle.$(MAN3EXT)',
                                               'lib/DBD/Oracle/Troubleshooting/Win32.pod' => '$(INST_MAN3DIR)\\DBD.Oracle.Troubleshooting.Win32.$(MAN3EXT)'
                                             },
                               'INSTALLSITEMAN1DIR' => '$(INSTALLMAN1DIR)',
                               'OBJ_EXT' => '.o',
                               'SHAR' => 'shar',
                               'dist' => $dbd_oracle_mm_opts->{'dist'},
                               'DESTINSTALLSCRIPT' => '$(DESTDIR)$(INSTALLSCRIPT)',
                               'INSTALLARCHLIB' => 'C:\Users\magja\graphviz-build-utilities\\lib',
                               'LD' => 'g++',
                               'LIBPERL_A' => 'libperl.a',
                               'LIBC' => '',
                               'OSVERS' => '6.1',
                               'PREOP' => '$(NOECHO) $(NOOP)',
                               'PERM_DIR' => 755,
                               'DESTINSTALLVENDORLIB' => '$(DESTDIR)$(INSTALLVENDORLIB)',
                               'INST_BIN' => 'blib\\bin',
                               'INSTALLMAN3DIR' => 'C:\Users\magja\graphviz-build-utilities\\man\\man3',
                               'LIBS' => $dbd_oracle_mm_opts->{'LIBS'},
                               'DESTINSTALLMAN1DIR' => '$(DESTDIR)$(INSTALLMAN1DIR)',
                               'AR' => 'ar',
                               'INST_AUTODIR' => '$(INST_LIB)\\auto\\$(FULLEXT)',
                               'DESTINSTALLSITESCRIPT' => '$(DESTDIR)$(INSTALLSITESCRIPT)',
                               'PERLPREFIX' => 'C:\Users\magja\graphviz-build-utilities',
                               'RANLIB' => 'ranlib',
                               'INST_ARCHAUTODIR' => '$(INST_ARCHLIB)\\auto\\$(FULLEXT)',
                               'PERL_INC' => 'C:\Users\magja\graphviz-build-utilities\\lib\\CORE',
                               'CONFIG' => [
                                             'ar',
                                             'cc',
                                             'cccdlflags',
                                             'ccdlflags',
                                             'dlext',
                                             'dlsrc',
                                             'exe_ext',
                                             'full_ar',
                                             'ld',
                                             'lddlflags',
                                             'ldflags',
                                             'libc',
                                             'lib_ext',
                                             'obj_ext',
                                             'osname',
                                             'osvers',
                                             'ranlib',
                                             'sitelibexp',
                                             'sitearchexp',
                                             'so',
                                             'vendorarchexp',
                                             'vendorlibexp'
                                           ],
                               'BSLOADLIBS' => '',
                               'TARFLAGS' => 'cvf',
                               'C' => [
                                        'Oracle.c',
                                        'dbdimp.c',
                                        'oci8.c'
                                      ],
                               'BASEEXT' => 'Oracle',
                               'PERL_ARCHIVEDEP' => '$(PERL_INCDEP)\\libperl524.a',
                               'PERL_ARCHIVE_AFTER' => '',
                               'SO' => 'dll',
                               'RM_RF' => '$(ABSPERLRUN) -MExtUtils::Command -e rm_rf --',
                               'INST_MAN1DIR' => 'blib\\man1',
                               'EQUALIZE_TIMESTAMP' => '$(ABSPERLRUN) -MExtUtils::Command -e eqtime --',
                               'LD_RUN_PATH' => '',
                               'PREREQ_PM' => {
                                                'DBI' => '1.51'
                                              },
                               'DIST_CP' => 'best',
                               'XS_VERSION' => '1.74',
                               'PMLIBDIRS' => [
                                                'lib'
                                              ],
                               'INSTALLSITEMAN3DIR' => '$(INSTALLMAN3DIR)',
                               'MACROSTART' => '',
                               'NOECHO' => '@',
                               'INSTALLVENDORBIN' => '',
                               'VERSION' => '1.74',
                               'AR_STATIC_ARGS' => 'cr',
                               'PERL_CORE' => 0,
                               'RESULT' => [
                                             '# This Makefile is for the DBD::Oracle extension to perl.
#
# It was generated automatically by MakeMaker version
# 7.3 (Revision: 73000) from the contents of
# Makefile.PL. Don\'t edit this file, edit Makefile.PL instead.
#
#       ANY CHANGES MADE HERE WILL BE LOST!
#
#   MakeMaker ARGV: (q[INSTALLDIRS=perl])
#
',
                                             '#   MakeMaker Parameters:
',
                                             '#     ABSTRACT_FROM => q[lib/DBD/Oracle.pm]',
                                             '#     AUTHOR => [q[Tim Bunce (dbi-users@perl.org)]]',
                                             '#     BUILD_REQUIRES => {  }',
                                             '#     CONFIGURE_REQUIRES => {  }',
                                             '#     DEFINE => q[ -Wall -Wno-comment -DUTF8_SUPPORT -DORA_OCI_VERSION=\\"12.2.0.1\\" -DORA_OCI_102 -DORA_OCI_112]',
                                             '#     DIR => []',
                                             '#     INC => q[-IC:/cygwin/home/gecko/AP-5.24.3.2404-MSWin32-x64-404865/oracle-instantclient-win64/sdk/include -IC:/cygwin/home/gecko/AP-5.24.3.2404-MSWin32-x64-404865/oracle-instantclient-win64/rdbms/demo -IC:\Users\magja\graphviz-build-utilities\\lib\\auto\\DBI]',
                                             '#     LIBS => [q[-LC:/cygwin/home/gecko/AP-5.24.3.2404-MSWin32-x64-404865/DBD-Oracle -loci]]',
                                             '#     LICENSE => q[perl]',
                                             '#     META_MERGE => { build_requires=>{ DBI=>q[1.51], ExtUtils::MakeMaker=>q[0], Test::Simple=>q[0.90] }, configure_requires=>{ DBI=>q[1.51] }, resources=>{ bugtracker=>{ mailto=>q[bug-dbd-oracle at rt.cpan.org], web=>q[http://rt.cpan.org/Public/Dist/Display.html?Name=DBD-Oracle] }, homepage=>q[http://search.cpan.org/dist/DBD-Oracle], repository=>{ type=>q[git], url=>q[git://github.com/yanick/DBD-Oracle.git], web=>q[http://github.com/yanick/DBD-Oracle/tree] } } }',
                                             '#     NAME => q[DBD::Oracle]',
                                             '#     OBJECT => q[$(O_FILES)]',
                                             '#     PREREQ_PM => { DBI=>q[1.51] }',
                                             '#     TEST_REQUIRES => {  }',
                                             '#     VERSION_FROM => q[lib/DBD/Oracle.pm]',
                                             '#     clean => { FILES=>q[xstmp.c Oracle.xsi dll.base dll.exp sqlnet.log libOracle.def mk.pm DBD_ORA_OBJ.*] }',
                                             '#     dist => { COMPRESS=>q[gzip -v9], DIST_DEFAULT=>q[clean distcheck disttest tardist], PREOP=>q[$(MAKE) -f Makefile.old distdir], SUFFIX=>q[gz] }',
                                             '
# --- MakeMaker post_initialize section:'
                                           ],
                               'MAP_TARGET' => 'perl',
                               'INSTALLSCRIPT' => 'C:\Users\magja\graphviz-build-utilities\\bin',
                               'INSTALLSITESCRIPT' => 'C:\Users\magja\graphviz-build-utilities\\site\\bin',
                               'LINKTYPE' => 'dynamic',
                               'FULLEXT' => 'DBD\\Oracle',
                               'CCCDLFLAGS' => ' ',
                               'OBJECT' => '$(O_FILES)',
                               'EXTRALIBS' => '"liboci.a" "C:\\MinGW\\x86_64-w64-mingw32\\lib\\libmoldname.a" "C:\\MinGW\\x86_64-w64-mingw32\\lib\\libkernel32.a" "C:\\MinGW\\x86_64-w64-mingw32\\lib\\libuser32.a" "C:\\MinGW\\x86_64-w64-mingw32\\lib\\libgdi32.a" "C:\\MinGW\\x86_64-w64-mingw32\\lib\\libwinspool.a" "C:\\MinGW\\x86_64-w64-mingw32\\lib\\libcomdlg32.a" "C:\\MinGW\\x86_64-w64-mingw32\\lib\\libadvapi32.a" "C:\\MinGW\\x86_64-w64-mingw32\\lib\\libshell32.a" "C:\\MinGW\\x86_64-w64-mingw32\\lib\\libole32.a" "C:\\MinGW\\x86_64-w64-mingw32\\lib\\liboleaut32.a" "C:\\MinGW\\x86_64-w64-mingw32\\lib\\libnetapi32.a" "C:\\MinGW\\x86_64-w64-mingw32\\lib\\libuuid.a" "C:\\MinGW\\x86_64-w64-mingw32\\lib\\libws2_32.a" "C:\\MinGW\\x86_64-w64-mingw32\\lib\\libmpr.a" "C:\\MinGW\\x86_64-w64-mingw32\\lib\\libwinmm.a" "C:\\MinGW\\x86_64-w64-mingw32\\lib\\libversion.a" "C:\\MinGW\\x86_64-w64-mingw32\\lib\\libodbc32.a" "C:\\MinGW\\x86_64-w64-mingw32\\lib\\libodbccp32.a" "C:\\MinGW\\x86_64-w64-mingw32\\lib\\libcomctl32.a"',
                               'MM_VERSION' => '7.3',
                               'UNINSTALL' => '$(ABSPERLRUN) -MExtUtils::Command::MM -e uninstall --',
                               'MAKEFILE_OLD' => 'Makefile.old',
                               'ARGS' => {
                                           'META_MERGE' => $dbd_oracle_mm_opts->{'META_MERGE'},
                                           'PREREQ_PM' => $dbd_oracle_mm_opts->{'PREREQ_PM'},
                                           'dist' => $dbd_oracle_mm_opts->{'dist'},
                                           'clean' => $dbd_oracle_mm_opts->{'clean'},
                                           'INSTALLDIRS' => 'perl',
                                           'LIBS' => $dbd_oracle_mm_opts->{'LIBS'},
                                           'INC' => '-IC:/cygwin/home/gecko/AP-5.24.3.2404-MSWin32-x64-404865/oracle-instantclient-win64/sdk/include -IC:/cygwin/home/gecko/AP-5.24.3.2404-MSWin32-x64-404865/oracle-instantclient-win64/rdbms/demo -IC:\Users\magja\graphviz-build-utilities\\lib\\auto\\DBI',
                                           'ABSTRACT_FROM' => 'lib/DBD/Oracle.pm',
                                           'OBJECT' => '$(O_FILES)',
                                           'DEFINE' => ' -Wall -Wno-comment -DUTF8_SUPPORT -DORA_OCI_VERSION=\\"12.2.0.1\\" -DORA_OCI_102 -DORA_OCI_112',
                                           'AUTHOR' => $dbd_oracle_mm_self->{'AUTHOR'},
                                           'VERSION_FROM' => 'lib/DBD/Oracle.pm',
                                           'DIR' => $dbd_oracle_mm_opts->{'DIR'},
                                           'NAME' => 'DBD::Oracle',
                                           'LICENSE' => 'perl'
                                         },
                               'DESTINSTALLPRIVLIB' => '$(DESTDIR)$(INSTALLPRIVLIB)',
                               'CCDLFLAGS' => ' ',
                               'CONFIGURE_REQUIRES' => {},
                               'ABSPERL' => '$(PERL)',
                               'CP_NONEMPTY' => '$(ABSPERLRUN) -MExtUtils::Command::MM -e cp_nonempty --',
                               'PMLIBPARENTDIRS' => [
                                                      'lib'
                                                    ],
                               'XS' => {
                                         'Oracle.xs' => 'Oracle.c'
                                       },
                               'INSTALLVENDORHTMLDIR' => 'C:\Users\magja\graphviz-build-utilities\\html',
                               'LICENSE' => 'perl',
                               'RCS_LABEL' => 'rcs -Nv$(VERSION_SYM): -q',
                               'H' => [
                                        'Oracle.h',
                                        'dbdimp.h',
                                        'dbivport.h',
                                        'ocitrace.h'
                                      ],
                               'INST_HTMLDIR' => 'blib\\html',
                               'INSTALLPRIVLIB' => 'C:\Users\magja\graphviz-build-utilities\\lib',
                               'DESTINSTALLSITEBIN' => '$(DESTDIR)$(INSTALLSITEBIN)',
                               'TEST_S' => '$(ABSPERLRUN) -MExtUtils::Command::MM -e test_s --',
                               'DESTINSTALLVENDORMAN3DIR' => '$(DESTDIR)$(INSTALLVENDORMAN3DIR)',
                               'INSTALLMAN1DIR' => 'C:\Users\magja\graphviz-build-utilities\\man\\man1',
                               'DEFINE' => ' -Wall -Wno-comment -DUTF8_SUPPORT -DORA_OCI_VERSION=\\"12.2.0.1\\" -DORA_OCI_102 -DORA_OCI_112',
                               'DIST_DEFAULT' => 'tardist',
                               'DESTINSTALLBIN' => '$(DESTDIR)$(INSTALLBIN)',
                               'FALSE' => '$(ABSPERLRUN)  -e "exit 1" --',
                               'LIB_EXT' => '.a',
                               'HAS_LINK_CODE' => 1,
                               'ABSTRACT' => 'Oracle database driver for the DBI module',
                               'INST_STATIC' => '$(INST_ARCHAUTODIR)\\$(BASEEXT)$(LIB_EXT)',
                               'ABSTRACT_FROM' => 'lib/DBD/Oracle.pm',
                               'MAN3EXT' => '3',
                               'DESTINSTALLSITELIB' => '$(DESTDIR)$(INSTALLSITELIB)'
                             }, 'PACK001' );
